# config
logo: /images/runnerty.png
keywords: "runnerty, scheduler, task, task manager, automation, job, notifications, executions, sysadmin, tools, logs, log, reload, programmatic, production, monitoring, process manager, profiling, cron, devops, dev ops"
pubkey: 13DB CAA1 2633 81A7
sections: 
  HOME:
    items:
      quick start: /docs/
      config: /config
      plan: /plan
      chains: /chains
      triggers: /triggers
      process: /process
      dependencies: /dependencies
      executors: /executors
      notifiers: /notifiers 
      values: /values
      functions: /functions
      queues: /queues
      plugins: /plugins
      API: /api

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics: UA-99090757-1

social:
 github: https://github.com/Coderty/runnerty
 twitter: https://twitter.com/runnerty_io
 npm: https://www.npmjs.com/package/runnerty
 slack: https://runnerty.slack.com/shared_invite/MTgxNDQ2NTk2NTk3LTE0OTQ0MTIxMDMtOGRkYWQyNzEyOA
